version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-chat-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      # REMOVE the line below to prevent postgres from creating a non-existent database.
      - POSTGRES_DB=${DB_NAME:-aichat}
    ports:
      - "${DB_PORT:-5432}:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
